// <auto-generated />
namespace Casentra.RMATicketing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeset23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeset23));
        
        string IMigrationMetadata.Id
        {
            get { return "201705051010510_changeset-23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
