// <auto-generated />
namespace Casentra.RMATicketing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class chanageset09 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chanageset09));
        
        string IMigrationMetadata.Id
        {
            get { return "201703070649130_chanageset-09"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
